[package]
name = "http-profiler"
version = "0.1.0"
edition = "2021"

[dependencies]
quinn = "0.11.1"
reqwest = { version = "0.12.4", features = ["json", "http2"] }
tokio = { version = "1.37.0", features = ["rt-multi-thread", "macros"] }
